// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

import './App.css'
;

function App(Props) {
  return React.createElement("div", {
              className: "App"
            }, React.createElement("div", undefined, React.createElement("a", {
                      href: "https://vitejs.dev",
                      target: "_blank"
                    }, React.createElement("img", {
                          className: "logo",
                          alt: "Vite logo",
                          src: "/vite.svg"
                        })), React.createElement("a", {
                      href: "https://reactjs.org",
                      target: "_blank"
                    }, React.createElement("img", {
                          className: "logo react",
                          alt: "React logo",
                          src: "./assets/react.svg"
                        }))), React.createElement("h1", undefined, "Vite + React"), React.createElement("div", {
                  className: "card"
                }, React.createElement("button", undefined, "count is"), React.createElement("p", undefined, "Edit", React.createElement("code", undefined, "src/App.res"), "and save to test HMR")), React.createElement("p", {
                  className: "read-the-docs"
                }, "Click on the Vite and React logos to learn more"));
}

var make = App;

export {
  make ,
}
/*  Not a pure module */
